version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: gustavofdeoliveira/p4-backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3001:3001"

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    image: gustavofdeoliveira/p4-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
